version: '3.7'
services:
  api-server:
    build: .
    tty: true
    restart: always
    ports:
      - '3004:3000'
    volumes:
      - type: bind
        source: ./nest-sandbox
        target: /api-server
    depends_on:
      - db-server

  db-server:
    container_name: db-server
    image: mysql:5.7.29
    restart: always
    ports:
      - '33306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: password
